using Langscaper_Core.Phonology;

namespace Langscaper_Core.Services
{
    public static class PhonemeNotationService
    {
        public static readonly Dictionary<Phoneme, string> PhonemeToIPA = new()
        {
            { Phoneme.VoicedBilabialNasal, "m" },
            { Phoneme.VoicedLabioDentalNasal, "ɱ" },
            { Phoneme.VoicedAlveolarNasal, "n" },
            { Phoneme.VoicedRetroflexNasal, "ɳ" },
            { Phoneme.VoicedPalatalNasal, "ɲ" },
            { Phoneme.VoicedVelarNasal, "ŋ" },
            { Phoneme.VoicedUvularNasal, "ɴ" },
            { Phoneme.VoicelessBilabialPlosive, "p" },
            { Phoneme.VoicedBilabialPlosive, "b" },
            { Phoneme.VoicelessAlveolarPlosive, "t" },
            { Phoneme.VoicedAlveolarPlosive, "d" },
            { Phoneme.VoicelessRetroflexPlosive, "ʈ" },
            { Phoneme.VoicedRetroflexPlosive, "ɖ" },
            { Phoneme.VoicelessPalatalPlosive, "c" },
            { Phoneme.VoicedPalatalPlosive, "ɟ" },
            { Phoneme.VoicelessVelarPlosive, "k" },
            { Phoneme.VoicedVelarPlosive, "ɡ" },
            { Phoneme.VoicelessUvularPlosive, "q" },
            { Phoneme.VoicedUvularPlosive, "ɢ" },
            { Phoneme.VoicelessGlottalPlosive, "ʔ" },
            { Phoneme.VoicelessBilabialFricative, "ɸ" },
            { Phoneme.VoicedBilabialFricative, "β" },
            { Phoneme.VoicelessLabioDentalFricative, "f" },
            { Phoneme.VoicedLabioDentalFricative, "v" },
            { Phoneme.VoicelessDentalFricative, "θ" },
            { Phoneme.VoicedDentalFricative, "ð" },
            { Phoneme.VoicelessAlveolarFricative, "s" },
            { Phoneme.VoicedAlveolarFricative, "z" },
            { Phoneme.VoicelessPostAlveolarSibilantFricative, "ʃ" },
            { Phoneme.VoicedPostAlveolarSibilantFricative, "ʒ" },
            { Phoneme.VoicelessRetroflexFricative, "ʂ" },
            { Phoneme.VoicedRetroflexFricative, "ʐ" },
            { Phoneme.VoicelessPalatalFricative, "ç" },
            { Phoneme.VoicedPalatalFricative, "ʝ" },
            { Phoneme.VoicelessVelarFricative, "x" },
            { Phoneme.VoicedVelarFricative, "ɣ" },
            { Phoneme.VoicelessUvularFricative, "χ" },
            { Phoneme.VoicedUvularFricative, "ʁ" },
            { Phoneme.VoicelessPharyngealFricative, "ħ" },
            { Phoneme.VoicedPharyngealFricative, "ʕ" },
            { Phoneme.VoicelessGlottalFricative, "h" },
            { Phoneme.VoicedGlottalFricative, "ɦ" },
            { Phoneme.VoicedLabioDentalApproximant, "ʋ" },
            { Phoneme.VoicedAlveolarApproximant, "ɹ" },
            { Phoneme.VoicedRetroflexApproximant, "ɻ" },
            { Phoneme.VoicedPalatalApproximant, "j" },
            { Phoneme.VoicedLabioVelarApproximant , "w" },
            { Phoneme.VoicedVelarApproximant, "ɰ" },
            { Phoneme.VoicedBilabialTrill, "ʙ" },
            { Phoneme.VoicedAlveolarTrill, "r" },
            { Phoneme.VoicedUvularTrill, "ʀ" },
            { Phoneme.Voicedlabiodentalflap, "ⱱ" },
            { Phoneme.VoicedAlveolarTap, "ɾ" },
            { Phoneme.VoicedRetroflexTap, "ɽ" },
            { Phoneme.VoicelessAlveolarLateralFricative, "ɬ" },
            { Phoneme.VoicedAlveolarLateralFricative, "ɮ" },
            { Phoneme.VoicedAlveolarLateralApproximant, "l" },
            { Phoneme.VoicedRetroflexLateralApproximant, "ɭ" },
            { Phoneme.VoicedPalatalLateralApproximant, "ʎ" },
            { Phoneme.VoicedVelarLateralApproximant, "ʟ" },
            { Phoneme.CloseFrontUnrounded , "i" },
            { Phoneme.CloseFrontRounded , "y" },
            { Phoneme.CloseCentralUnrounded , "ɨ" },
            { Phoneme.CloseCentralRounded , "ʉ" },
            { Phoneme.CloseBackUnrounded , "ɯ" },
            { Phoneme.CloseBackRounded , "u" },
            { Phoneme.NearCloseFrontUnrounded , "ɪ" },
            { Phoneme.NearCloseFrontRounded , "ʏ" },
            { Phoneme.NearCloseBackRounded , "ʊ" },
            { Phoneme.CloseMidFrontUnrounded , "e" },
            { Phoneme.CloseMidFrontRounded , "ø" },
            { Phoneme.MidCentral , "ə" },
            { Phoneme.OpenMidFrontUnrounded , "ɛ" },
            { Phoneme.OpenMidFrontRounded , "œ" },
            { Phoneme.OpenMidBackUnrounded , "ʌ" },
            { Phoneme.OpenMidBackRounded , "ɔ" },
            { Phoneme.NearOpenFrontUnrounded , "æ" },
            { Phoneme.OpenFrontUnrounded , "a" },
            { Phoneme.OpenBackUnrounded , "ɑ" },
            { Phoneme.OpenBackRounded , "ɒ" }
        };
    }
}
